version: "3.6"

services:
  # PostgreSQL Server for Hasura
  hasura-db:
    container_name: hasura-db
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_DB: "hasura"
      POSTGRES_USER: "hasura"
      POSTGRES_PASSWORD: "hasura"
    volumes:
      - ./.database/hasura:/var/lib/postgresql/data

  # Hasura
  hasura:
    container_name: hasura
    image: hasura/graphql-engine:v2.0.10
    ports:
      - "8080:8080"
    depends_on:
      - hasura-db
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hasura:hasura@hasura-db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "1qazxsw2@WSXZAQ!" # comment out to make admin console public
      # un-comment the following line to activate JWT Authentication:
      # HASURA_GRAPHQL_JWT_SECRET: '{ "type": "RS256", "jwk_url": "http://keycloak:8080/auth/realms/master/protocol/openid-connect/certs" }'
    volumes:
      - ".hasura:/hasura"

  # PostgreSQL Server for Keycloak
  keycloak-db:
    container_name: keycloak-db
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "keycloak"
    volumes:
      - ./.database/keycloak:/var/lib/postgresql/data

  # Keycloak
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - "9090:8080"
    depends_on:
      - keycloak-db
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      DB_VENDOR: "postgres"
      DB_ADDR: "keycloak"
      DB_USER: "keycloak"
      DB_PASSWORD: "keycloak"

  # Hasura Action
  keycloak-hasura-action:
    build:
      context: keycloak-hasura-action
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      KEYCLOAK_HOST: "http://keycloak:8080"
      KEYCLOAK_ADMIN_USER: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"

  # Hasura Remote Schema
  keycloak-hasura-remote-schema:
    build:
      context: keycloak-hasura-remote-schema
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      KEYCLOAK_HOST: "http://keycloak:8080"
      KEYCLOAK_ADMIN_USER: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
# volumes:
#   pg_hausra_data:
#   keycloak-db_data:
